# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://aierlab.tech
title: AierLab - Advancing AI Research and Development
email: hobart.yang@qq.com
author: Haobo Yang
description: > 
  Welcome to AierLab! We are committed to pioneering advancements in AI, focusing on research that bridges theoretical insights with practical applications. Our aim is to develop AI technologies that are not only powerful but are also aligned with ethical standards and human values.
copyright: 'Copyright &copy; 2024 Haobo Yang. All Rights Reserved. Licensed under Creative Commons.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/AierLab
  - title: linkedin
    url: https://www.linkedin.com/company/aierlab
  - title: discord
    url: https://discord.gg/nn5NDXMgae
